### ISSUE TITLE
Файлы стилей

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#10]
![1](https://user-images.githubusercontent.com/19621113/74944757-8b7dc080-5407-11ea-8cf9-7d38725586b8.png)
Сейчас в проекте стили компонентов слишком раздроблены, а учитывая, что проект учебный и компоненты сами по себе компактные, получается не слишком удобно ) Думаю, лучше объединить файлы со стилями в единый стилевой файл блока, внутри которого через амперсанд будут прописаны правила для элементов / модификаторов.
К тому же это поможет тебе решить проблему с переопределением правил для модификаторов после настройки автоимпорта стилевых файлов

**Comment by nelliza** [comment]
Не совсем так: класс блока ты указываешь на верхней строчке, а в именах элементов / модификаторов уже не дублируешь, а используешь ссылку на родительский селектор с помощью амперсанда `&`

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/75316850-7d042e80-5877-11ea-88ef-77ebe252ce92.png)
Также при указании правил для модификаторов не нужно использовать комбинированные селекторы (имя блока + имя модификатора), достаточно указания только имени модификатора

**Comment by nelliza** [comment]
Плюс в папке страниц стили элементов все так же разбросаны по разным файлам

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76147276-ad37a280-60ab-11ea-8323-0e9f975c73ef.png)
Лучше сначала указывать правила для самого класса, а ниже для псевдоклассов / псевдоэлементов

**Comment by nelliza** [comment]
![2](https://user-images.githubusercontent.com/19621113/76147289-d6583300-60ab-11ea-99c9-f554ee008cdd.png)
Переменные лучше объявлять вверху, тем более что это значение у тебя используется выше )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76699005-d82c8280-66b9-11ea-95b8-7d61e55e7805.png)
Модификаторы лучше располагать сразу после основных блоков / элементов, так наглядно видны стили сразу во всех возможных состояниях

Заметила такое во многих блоках, пройдись пожалуйста по всему проекту

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76699067-a831af00-66ba-11ea-9e48-98661f0ab2b0.png)
Модификаторы лучше располагать сразу после основных блоков / элементов, так наглядно видны стили сразу во всех возможных состояниях

Заметила такое во многих блоках, пройдись пожалуйста по всему проекту

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76699083-d1523f80-66ba-11ea-8732-ed73353dfcf8.png)
Здесь скорее всего должны быть модификаторы типа "ключ-значение" вместо булевых
