### ISSUE TITLE
Страница подбора номера

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#11]
![1](https://user-images.githubusercontent.com/19621113/75017851-eb737600-549e-11ea-857d-a37f47c7642b.png)
А что это за зеленые цифры на изображениях номеров? ) Не сталкивалась с подобным, это же не предусмотрено макетом )

**Comment by SergeyVN94** [comment]
В issues 5 посмотри. Мне сказали, что надо показать смену картинок.

**Comment by Nelliza** [comment]
Ок, давай тогда так и оставим пока
