### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#12]
![1](https://user-images.githubusercontent.com/19621113/75317091-23503400-5878-11ea-80ad-53d2f6261e96.png)

Первый пункт [HTML-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md):
> # HTML:
>   1. Отступы делать пробелами, на проекте во всех файлах html, pug, etc должен быть одинаковый отступ — либо 4, либо 2 пробела;

Пройдись по всему проекту и исправь везде пожалуйста

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/75317581-6d85e500-5879-11ea-83ce-f3debaa27399.png)
Вместо этой конструкции:
```
let headClassList = '';
if (bottom !== '') headClassList += 'bullet-list__head_bottom_bg';
```
легче сразу прописать класс для `headClassList` (почему `classList`, кстати, если там всего один класс прописывается? :)) в зависимости от наличия `bottom`:
```
const headClass = bottom ? `bullet-list__head_bottom_${bottom}` : false;
```
Только имя у `bottom` нужно поменять на более очевидное, и у модификатора тоже

**Comment by Nelliza** [comment]
Да и в целом есть ли смысл в таких конструкциях `bottom !== ''`, `head !== ''`? Почему бы не ставить в зависимость от наличия `bottom`, `head` и т.д.

**Comment by nelliza** [comment]
А `head` вообще у тебя по идее должен иметь булево значение, т.к. он либо есть, либо его нет, и именование тоже должно быть соответствующим

**Comment by nelliza** [comment]
В файлах html / pug используем двойные кавычки, а в стилевых - одинарные, исправь пожалуйста везде

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76699341-900f5f00-66bd-11ea-8d1c-374b181388f5.png)

> 7. **Названия шрифтов, содержащие пробелы, цифры или знаки пунктуации кроме дефисов заключать в кавычки**;

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/77229832-23a2cd00-6ba1-11ea-9886-20d31b7c7aad.png)
А все-таки никак не могу с тобой согласиться по поводу именования этого модификатора - почему `head_bottom_big`, если ты добавляешь к заголовку отступ снизу? )
