### ISSUE TITLE
Структура проекта

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#13]
![1](https://user-images.githubusercontent.com/19621113/76146656-9db55b00-60a5-11ea-9aaa-8fcdf003fd5e.png)
Сейчас структура проекта излишне переусложнена, такой код тяжело поддерживать и расширять. Для каждого блока следует создать один скриптовый файл с классом, в котором будет реализована логика для работы с самим блоком и его дочерними элементами

**Comment by nelliza** [comment]
Молодец, хорошую работу проделал, намного чище стал код 👍

Давай еще немного "причешем" проект: **html-body**, **container-content**, **page-container** - это не компоненты, а просто стилевые файлы, их надо вынести из папки компонентов. У тебя есть уже папка _styles_, вот туда можно перенести. Думаю, их даже можно объединить в один файл и назвать его как-нибудь _base.scss_ или _common.scss_, например

**Comment by Nelliza** [comment]
Дальше по изображениям: если они являются частью реализации конкретного блока, они должны лежать внутри папки этого блока, а в общую папку _images_ в корне кладутся только общие для проекта в целом или нескольких его блоков изображения

**Comment by nelliza** [comment]
Дальше по изображениям: если они являются частью реализации конкретного блока, они должны лежать внутри папки этого блока, а в общую папку _images_ в корне кладутся только общие для проекта в целом или нескольких его блоков изображения

Плюс имена файлов с изображениями желательно чтобы были более осмысленными, чем просто цифры ) Именоваться при этом они должны в `lower-case-hyphenated` стиле, по аналогии со шрифтовыми файлами

**Comment by nelliza** [comment]
Интерфейсы желательно именовать с заглавной буквы "I" в начале. Это хоть и не обязательное условие, но является рекомендуемой и широко распространенной практикой

**Comment by nelliza** [comment]
Согласно [стайлгайду от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#naming--filename-matches-export), название файла должно совпадать с именем класса (т.е. быть в `PascalCase`-нотации). Для скриптовых файлов, не содержащих классы, лучше придерживаться `camelCase`-нотации

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/76698642-a534bf80-66b6-11ea-8ff5-76f1ecccd3e9.png)
В блоке _logo_ svg-файлы следует также перенести в подпапку _images_

**Comment by Nelliza** [comment]
> Согласно [стайлгайду от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#naming--filename-matches-export), название файла должно совпадать с именем класса (т.е. быть в `PamelCase`-нотации). Для скриптовых файлов, не содержащих классы, лучше придерживаться `camelCase`-нотации

Все хорошо, кроме этой части - файлы с классами должны именоваться в `PamelCase`-нотации, как и сами классы

**Comment by nelliza** [comment]
> Согласно [стайлгайду от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#naming--filename-matches-export), название файла должно совпадать с именем класса (т.е. быть в `PascalCase`-нотации). Для скриптовых файлов, не содержащих классы, лучше придерживаться `camelCase`-нотации

Все хорошо, кроме этой части - файлы с классами должны именоваться в `PascalCase`-нотации, как и сами классы

**Comment by nelliza** [comment]
**RoomAmenities** - название файла и класса не соответствует именованию компонента

**Comment by nelliza** [comment]
Для единообразия именование pug-файлов в директории со страницами лучше сделать аналогичным именованию стилевых файлов (**landing-page.pug**, **registration.pug** и т.д.)

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/83340056-6b01b400-a2dc-11ea-9969-a5364d010e1d.png)
По аналогии со стилевыми файлами - давай не будем дробить файлы по БЭМ-элементам, только по блокам
