### ISSUE TITLE
Шрифты

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#16]
> 1. **Все картинки, шрифты и тд должны иметь уникальное название в рамках проекта и не содержать кириллических символов. Если в проекте нет индивидуальных соглашений, то они должны именоваться в стиле lower-case-hyphenated**;

Поправь именование шрифтовых файлов в соответствии с этим пунктом, плиз

**Comment by Nelliza** [comment]
По нашим стандартам формат `woff2` для шрифтов является обязательным:
> 2. **Если не требуется поддержка старых браузеров, шрифты должны быть в форматах `.woff2`, `.woff`. Сначала подключать `.woff2` шрифты, затем — `.woff` (пример ниже)**;

**Comment by nelliza** [comment]
По нашим стандартам формат `woff2` для шрифтов является обязательным, подключи его тоже плиз:
> 2. **Если не требуется поддержка старых браузеров, шрифты должны быть в форматах `.woff2`, `.woff`. Сначала подключать `.woff2` шрифты, затем — `.woff` (пример ниже)**;

**Comment by nelliza** [comment]
Еще заметила, что у тебя в **button.scss** для каждого модификатора кнопки семейство шрифтов подключается отдельно, хотя в большинстве случаев используется одно и то же семейство. Тут проще, я считаю, вынести это правило к самому блоку:
```css
font-family: Montserrat, Arial, sans-serif;
```
и оставить только переопределение на `'Material Icons'` для пары-тройки остальных модификаторов

**Comment by Nelliza** [comment]
Первыми требуется подключать `woff2`, и только затем — `woff`

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/77c14cedded67a2ec43141a49b3065ca25d45666/src/styles/mixins.scss#L80-L88
Первыми требуется подключать `woff2`, и только затем - `woff`
