### ISSUE TITLE
Календарь

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#17]
Не доступные для выбора даты должны быть "задизейблены" по аналогии с тем, как у тебя сейчас реализовано с днями прошлого месяца на календаре текущего:
![1](https://user-images.githubusercontent.com/19621113/76699548-81c24280-66bf-11ea-8bc3-e2edf9c6b6ef.gif)

Т.к. сейчас при клике на них создается ощущение, что календарь не работает: внешне они доступны для выбора, а по факту - нет

**Comment by nelliza** [comment]
Месяцы отображаются некорректно:
![1](https://user-images.githubusercontent.com/19621113/77228769-a5dbc300-6b9a-11ea-955e-bb7787b54914.gif)

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/78186673-ca2a8000-7475-11ea-866e-816c312a1a1f.gif)
После указания диапазона я не могу выбрать начальную дату больше той, которая указана в диапазоне

**Comment by nelliza** [comment]
Что-то опять с календарем ) Сейчас можно выбрать дату прибытия позже даты отъезда
![1](https://user-images.githubusercontent.com/19621113/79602066-803ace80-80f2-11ea-8aad-2dd5204a428e.gif)

**Comment by Nelliza** [comment]
Опять пришли к тому, с чего начали - не доступные для выбора даты правильнее будет "задизейблить" )
