### ISSUE TITLE
Проект не слинкован

### ISSUE THREAD

**Issue by safr** [SergeyVN94/site2#2]
Все страницы проекта нужно залинковать между собой чтобы с index.html  я мог перейти на любую страницу, а не открывать каждую страницу отдельно

**Comment by SergeyVN94** [comment]
т.е нужно сделать отдельную страницу для ссылок вместо readme.md?

**Comment by safr** [comment]
когда я захожу на index.html я кликаю на Войти и он должен переходить на страницу Войти и так далее, чтобы ощущалась целостность проекта.

**Comment by SergeyVN94** [comment]
1) в какое место добавлять ссылку на ui-kit, room-details, landing-page?
2) как тебя зовут в телеграме?

**Comment by safr** [comment]
В шапке сайта можешь добавить ссылку на ui kit,  при клике на подобрать номер должен перейти на страницу rooms, при клике на отдельный номер перейти на room-details,  в этом и есть суть проблемы, чтобы я сам в интерфейсе мог переходить по страницам

**Comment by SergeyVN94** [comment]
Готово.
