### ISSUE TITLE
Переполнение

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#31]
При добавлении столбцов нижнее меню отображается не очень некорректно, здесь лучше предусмотреть перенос блоков вниз при переполнении
![1](https://user-images.githubusercontent.com/19621113/79601014-cdb63c00-80f0-11ea-98ea-93b5123360eb.png)

**Comment by nelliza** [comment]
Вот еще вариант некорректного отображения при переполнении, теперь уже текста:
![1](https://user-images.githubusercontent.com/19621113/79602668-9006e280-80f3-11ea-85c8-6a0cff8c09d9.png)

**Comment by nelliza** [comment]
Что-то как-то не очень опять (
![1](https://user-images.githubusercontent.com/19621113/80146323-5da92980-85ba-11ea-893d-4d1215f544c7.png)

**Comment by Nelliza** [comment]
Верстка футера поехала:
![1](https://user-images.githubusercontent.com/19621113/80616450-9a0cd780-8a49-11ea-8c56-aad31dcf93a7.png)
