### ISSUE TITLE
PerfectPixel

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#32]
Выложи пожалуйста скрин макета с наложенным PerfectPixel (желательно в инверсии) и с открытым окошком настроек

**Comment by SergeyVN94** [comment]
![page_filter_pp](https://user-images.githubusercontent.com/33756004/79775468-f6cb0c80-833c-11ea-93e8-a93e309f207f.png)

**Comment by nelliza** [comment]
Небольшие замечания:
![1](https://user-images.githubusercontent.com/19621113/80034797-a51ab180-84f7-11ea-8256-b58a14617630.png)

**Comment by Nelliza** [comment]
![Uploading 2.png…]()

**Comment by nelliza** [comment]
![2](https://user-images.githubusercontent.com/19621113/80034849-b82d8180-84f7-11ea-96a9-ccac348f083d.png)
