### ISSUE TITLE
Именование

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#34]
![2](https://user-images.githubusercontent.com/19621113/80145629-27b77580-85b9-11ea-95cc-2128f8141811.png)
`Header-footer` - по-моему, не очень удачное имя для компонента )

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/80145858-85e45880-85b9-11ea-9ae0-1baad3a8c4dd.png)
Здесь тоже пример неудачного именования для ключа модификатора: ты пишешь `color`, но при этом значения совсем не похожи на цвета, тогда уж темы )

**Comment by nelliza** [comment]
> ![2](https://user-images.githubusercontent.com/19621113/80145629-27b77580-85b9-11ea-95cc-2128f8141811.png)
> `Header-footer` - по-моему, не очень удачное имя для компонента )

Здесь вообще такого блока не может быть в принципе: UI-kit - просто "сборная солянка" из компонентов, и вся эта секция никак не может рассматриваться как единый блок ([см. ишью # 36](https://github.com/SergeyVN94/site2/issues/36)):
![1](https://user-images.githubusercontent.com/19621113/80228148-53893880-8657-11ea-8fb4-bf67fbc4772a.png)

**Comment by Nelliza** [comment]
Здесь я бы рекомендовала вернуться к документации по БЭМ, в которой указано, что блок - это _"функционально независимый компонент страницы, который может быть **повторно использован**"_ ([ссылка](https://ru.bem.info/methodology/quick-start/#%D0%91%D0%BB%D0%BE%D0%BA))

**Comment by nelliza** [comment]
Еще по именованию:
![1](https://user-images.githubusercontent.com/19621113/80617918-574bff00-8a4b-11ea-870d-32dc75417fb3.png)

Здесь думаю уместнее `button-find` заменить на `search-button`

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/80618043-819dbc80-8a4b-11ea-83ec-9df6b139707c.png)
have-account -> has-account

Компонент buttons-demo -> demo-buttons

**Comment by nelliza** [comment]
Вообще посмотри плиз и исправь везде, где прилагательные идут после существительных (`menu-mobile-btn`, `btn-login` и т.д.)

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/bullet-list/bullet-list.pug#L16

`isCorrectMarginBottom` тоже не очень удачно, можно же просто `hasMarginBottom` в этом случае

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/bullet-list/bullet-list.pug#L28

Здесь опечатка

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/button/button.pug#L23

`disable` - это глагол, состояние будет `disabled`

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/calendar/calendar.pug#L24

Вот здесь тоже с именованием надо думать, слишком большая простыня получилась. Например, зачем здесь `.calendar__btn-change-month_action_next-month` дважды указывать слово `month`? Также `btn` тут лишнее, думаю, да и `action` не совсем подходящее слово для этого, тогда уж `direction`. Таким образом, можно оставить как-то так: `.calendar__change-month_direction_next`

**Comment by SergeyVN94** [comment]
838ba0290da3f6d43ba1db1312c5a51ab163c2ce

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/85fd1092171b920bbd8c1b278ca550b9a349b493/src/desktop.blocks/image-slider/image-slider.scss#L31
Поправь пожалуйста здесь тоже именование - модификатор именован не по БЭМ
