### ISSUE TITLE
Package.json

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#35]
Откорректируй пожалуйста разделение зависимостей: в `devDependencies` должны остаться только те зависимости, которые нужны исключительно для dev-режима, и отсутствие которых не помешает без проблем собрать проект в продакшн-режиме

**Comment by Nelliza** [comment]
`Webpack-cli` тоже думаю в `devDependencies` нужно

**Comment by Nelliza** [comment]
`Webpack-cli` тоже в `devDependencies` нужно перенести, думаю

**Comment by SergeyVN94** [comment]
490ad0d3cde2a8e4d9941281e6a261555acc9668
