### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#36]
![1](https://user-images.githubusercontent.com/19621113/80230081-15414880-865a-11ea-800f-f29fbc2cd514.png)
Такого блока быть не может, то же касается и секции с карточками: эти сущности не могут рассматриваться как единый блок, т.к. нельзя представить такой кейс, что их можно будет вставить в таком виде на страницу

Здесь я бы рекомендовала вернуться к документации по БЭМ, в которой указано, что блок - это _"функционально независимый компонент страницы, который может быть **повторно использован**"_ ([ссылка на доку](https://ru.bem.info/methodology/quick-start/#%D0%91%D0%BB%D0%BE%D0%BA))

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/80609174-798c4f80-8a40-11ea-8541-ac9c26892096.png)
![2](https://user-images.githubusercontent.com/19621113/80609188-7beea980-8a40-11ea-8bd0-d1da4af156f8.png)
![3](https://user-images.githubusercontent.com/19621113/80609195-7db86d00-8a40-11ea-85a6-0370056038b0.png)

Такого быть не должно - [миксин должен возвращать блок, а не элемент](https://rizzoma.com/topic/d5c429337bcaa70548fb5aeedee6d92b/0_b_8ndo_7tahq/)

**Comment by nelliza** [comment]
Блок `.container-content` у тебя болтается отдельно, так не должно быть. Все блоки должны быть оформлены в отдельный компонент с собственным миксином и стилями. И подключать ты его можешь соответственно инклюдом, как и любой другой миксин. Нужно подумать, стоит ли вообще выделять этот блок, либо, если стилизация с его помощью минимальна, в нем вообще нет нужды

**Comment by Nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/text/text.pug#L1-L41

Компонент **text** вообще не нужен, он так переусложнен кучей различных состояний, и при этом возвращает всего один `span` / `p`, без вложенных элементов, к тому же с разным текстовым содержимым и стилями. В чем же тогда его переиспользуемость? Это не блок по БЭМу, это обычный элемент `span / p`

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/490ad0d3cde2a8e4d9941281e6a261555acc9668/src/desktop.blocks/text/text.pug#L1-L41

Компонент **text** вообще не нужен, он так переусложнен кучей различных состояний, и при этом возвращает всего один `span` / `p`, без вложенных элементов, к тому же с разным текстовым содержимым и стилями. В чем же тогда его переиспользуемость? Это не блок по БЭМу, это обычный элемент `span / p`

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/commit/a6527ce5bc63d7f4a70869b07d30bca23c174219#r39258476

**Comment by Nelliza** [comment]
Также считаю, что **demo-buttons**, **demo-colors** и **demo-text** не должны рассматриваться как самостоятельные блоки по вышеуказанной причине

**Comment by nelliza** [comment]
Также считаю, что **demo-buttons**, **radio-buttons**, **toggle-buttons**, **like-buttons**, **rating-buttons** не должны рассматриваться как самостоятельные блоки по вышеуказанной причине

**Comment by nelliza** [comment]
`.ui-kit__demo-headers-and-footers-header`, `.ui-kit__demo-headers-and-footers-footer`, `.ui-kit__demo-headers-and-footers-copyright-bar` - здесь теперь неудачное именование, можно оставить просто `.ui-kit__demo-header`, `.ui-kit__demo-footer`, `.ui-kit__demo-copyright-bar`
