### ISSUE TITLE
Деструктуризация

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#38]
https://github.com/SergeyVN94/site2/blob/838ba0290da3f6d43ba1db1312c5a51ab163c2ce/src/desktop.blocks/social-icons/social-icons.pug#L16-L20
Вот этот код - лишний, зачем тебе деструктурировать этот объект, если ты передаешь в дочерний миксин `social-icon` все его поля? Тебе просто нужно миксин `social-icon` чуть подправить, чтобы он принимал объект в качестве параметра

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/838ba0290da3f6d43ba1db1312c5a51ab163c2ce/src/desktop.blocks/social-icons/social-icons.pug#L3-L11
Здесь же чуть выше тоже немного нелогично - получается, ты дважды назначаешь дефолтное значение для `icons`, правильнее будет так:
```
mixin social-icons(icons)
    -
        icons = icons || [...]
```

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/82466166-bb9d3400-9ac8-11ea-99a0-f0683408e690.png)
Куда-то делись иконки, не догадываешься, почему? )

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/50a9f4e98e4e8b6c82045eb803aed2e8b1b7c9b0/src/desktop.blocks/social-icon/social-icon.pug#L1
Вот это, кстати, небезопасно - пустой объект в качестве дефолтного значения резонно прописывать в случае, если для всех свойств принимаемого объекта предусмотрены значения по умолчанию. В противном случае есть риск не передать нужную инфу, в этом случае, например, значение нужной иконки

**Comment by SergeyVN94** [comment]
c41443207c0d449c62b07bf17e936da3a6691606

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/blob/c41443207c0d449c62b07bf17e936da3a6691606/src/desktop.blocks/dropdown-head/dropdown-head.pug#L4
Вот здесь опасно - что будет, если в `classes` будет передан не массив?

* * *
https://github.com/SergeyVN94/site2/blob/8f4ba64d860d979bdafc3379ea9fc1c432de324a/src/desktop.blocks/date-range/date-range.pug#L22-L23
Также передавать в качестве параметра само имя модификатора - не комильфо, это затрудняет поддержку кода, т.к. в случае переименования класса придется искать и править эти модификаторы по всему проекту. Тут правильнее передавать соответствующую опцию, в приведенном примере это может быть свойство `position` со значением `"left"`

**Comment by SergeyVN94** [comment]
42f7c2d9784597b9b00b6bf0a849bf61f39ebbd0

**Comment by nelliza** [comment]
Следует продумать, как сделать так, чтобы в модификаторы не попали не предусмотренные значения (для которых не заданы стили), чтобы в верстке не висели лишние классы-"пустышки"

**Comment by nelliza** [comment]
https://github.com/SergeyVN94/site2/commit/0187ee0554153813087fb849fbd6975e5db85e88#r40050689
