### ISSUE TITLE
Стили desktop.blocks

### ISSUE THREAD

**Issue by safr** [SergeyVN94/site2#4]
Стили компонентов подключаются в desktop.blocks/index.scss. Как рекомендация лучше каждый компонент где он используется подключать явно в pug файле через тег link

**Comment by SergeyVN94** [comment]
почему в pug а не через scss?

**Comment by safr** [comment]
мне кажется для большей явности, мы сразу видим к какому паг файлу какой сасс файл принадлежит

**Comment by SergeyVN94** [comment]
Я облазил гугл, но не нашел решения для загрузки scss в pug. 
link(rel="stylesheet", href='./block.scss') не работает.
Попробовал использовать require, но путь получается относительный + недоступны переменные из colors.scss. Куда копать, что бы решить проблему?

**Comment by safr** [comment]
Тогда оставь так пока
