### ISSUE TITLE
Юзабилити

### ISSUE THREAD

**Issue by safr** [SergeyVN94/site2#5]
При ховере, клике на кнопках, должны быть проставлены состояния hover, active, focus, также при клике на логотип я должен попадать на главную тобишь landing-page.pug. Также проверь это везде. В том числе клики на соц сети должны вести на главные страницы соц сетей.
Также как только открываю langing-page.pug нажимаю на таб и фокусируются элементы меню, это правильно. Но потом фокусировка резко переводит на футер. Но фокус должен сначала перейти на Войти, Зарегистрироваться а уже потом на футер.
На всех почти страницах подложка background должен растягиваться на всю страницу который под формой регистрации и войти.
В search-rooms буллеты слайдера переключаются а фотки нет. 
В пагинации сделай хотя бы чтобы при клике на номер он становился активным.

**Comment by SergeyVN94** [comment]
Какие css прописывать в hover, active, focus? В search-rooms фотки переключаются, просто там 4 одинаковых фото. Не понял, что должно быть в пагинации. Кнопка при клике должна обводиться цветом?

**Comment by safr** [comment]
в пагинации да все верно. если фотки переключаются, сделай какой нить fade чтоб было понятно что фотка новая. css для состояний придумай сам исходя из дизайна

**Comment by SergeyVN94** [comment]
Нужны hover, active, focus для radio, toggle, like кнопок и чекбоксов?

**Comment by safr** [comment]
да те элементы с которыми юзер взаимодействует отмечает, кликает и т.д

**Comment by SergeyVN94** [comment]
Tabindex для этих элементов нужен или он только для инпутов и ссылок?

**Comment by safr** [comment]
для инпутов и ссылок

**Comment by SergeyVN94** [comment]
Готово.

**Comment by SergeyVN94** [comment]
Сколько ждать следующих правок?
