### ISSUE TITLE
Типы полей

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#6]
Для полей форм с четким предназначением рекомендуется указывать соответствующий тип (`email`, `password`, `tel` и т.д.), об этом указано в [стандартах (п. 21)](https://github.com/fullstack-development/front-end-best-practices/blob/2555d6f787b2467ade9353a1278894667c1aefb5/HTML/tags.md)

**Comment by SergeyVN94** [comment]
В masked-text-field нужно вводить дату, но в виде строки. Тип date указывать?

**Comment by nelliza** [comment]
> В masked-text-field нужно вводить дату, но в виде строки. Тип date указывать?

Нет, я намеренно не указала этот тип, т.к. в этом макете действительно есть такая тема

**Comment by nelliza** [comment]
Просьба при именовании коммита перед номером ишью ставить хеш-символ, чтобы в самом ишью добавлялась ссылка на соответствующий коммит. Сейчас я с этой целью добавила комменты к коммитам ) Но в будущем плиз именуй так, с `#[issue number]` в конце
