### ISSUE TITLE
Атрибуты для ссылок

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#7]
Все ссылки на внешние ресурсы должны содержать атрибуты `target="_blank"` и `rel="noopener noreferrer"` ([п.п. 15-16 HTML-стандартов](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/tags.md)), добавь их плиз для социальных ссылок в футере

**Comment by SergeyVN94** [comment]
Готово.
