### ISSUE TITLE
Ошибки в консоли

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#8]
![1](https://user-images.githubusercontent.com/19621113/74762862-bd6c1700-528f-11ea-9c93-212dccd8d9b9.png)
Сейчас при загрузке страниц присутствуют ошибки в консоли, исправь их плиз

**Comment by SergeyVN94** [comment]
Варнинги тоже исправлять?

**Comment by SergeyVN94** [comment]
Ошибки исправил.

**Comment by nelliza** [comment]
> Варнинги тоже исправлять?

Нет, я имела в виду именно ошибки
