### ISSUE TITLE
Настроить автоимпорт

### ISSUE THREAD

**Issue by nelliza** [SergeyVN94/site2#9]
![1](https://user-images.githubusercontent.com/19621113/74763121-3ff4d680-5290-11ea-94a1-a4a439c1f172.png)
Вот такого быть не должно, следует настроить автоматический импорт стилевых и скриптовых файлов

**Comment by SergeyVN94** [comment]
Не понял задачу. Как именно должен происходить автоимпорт?

**Comment by Nelliza** [comment]
Если кратко, то в точке входа добавляешь функцию, которая реквайрит скриптовые и стилевые файлы, и уже не нужно будет прописывать их вручную при их добавлении

**Comment by nelliza** [comment]
> Не понял задачу. Как именно должен происходить автоимпорт?

Если кратко, то в точке входа добавляешь функцию, которая реквайрит скриптовые и стилевые файлы, и уже не нужно будет прописывать их вручную при их добавлении

**Comment by SergeyVN94** [comment]
Глобальные переменные в sass надо настраивать или можно импортировать в каждый файл отдельно?

**Comment by SergeyVN94** [comment]
Готово.

**Comment by nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/75347586-1c461780-58b2-11ea-89bb-baf06f8793c1.png)
![2](https://user-images.githubusercontent.com/19621113/75347587-1e0fdb00-58b2-11ea-8031-52951a565442.png)
А почему у тебя так и остались эти импорты во всех индексных файлах отдельных страниц? У тебя должна быть одна точка входа, в которой настроен автоимпорт, а отдельные ts-файлы с импортами для каждой страницы лишние

**Comment by nelliza** [comment]
Правила из 6-7 строк в **index.ts** можно объединить
